// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetFamily.Infrastructure.Adapters.Postgres;

#nullable disable

namespace PetFamily.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414152058_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetFamily.Core.Domain.Models.PetAggregate.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedOtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_otc");

                    b.Property<DateTime>("DateDelete")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateDelete");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HealthInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("health_info");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("isDelete");

                    b.Property<bool>("IsSterilized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sterilized");

                    b.Property<bool>("IsVaccined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vaccined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PetHelpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("pet_help_status");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_id");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "PetFamily.Core.Domain.Models.PetAggregate.Pet.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("city");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("house");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("region");
                        });

                    b.HasKey("Id")
                        .HasName("pK_pets");

                    b.HasIndex("VolunteerId")
                        .HasDatabaseName("iX_pets_volunteer_id");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("PetFamily.Core.Domain.Models.Species.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pK_species");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("PetFamily.Core.Domain.Models.SpeciesAggregate.Entity.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("breed_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pK_breeds");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("iX_breeds_species_id");

                    b.ToTable("breeds", (string)null);
                });

            modelBuilder.Entity("PetFamily.Core.Domain.Models.VolunteerAggregate.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_id");

                    b.Property<DateTime>("DateDelete")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateDelete");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("isDelete");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.ComplexProperty<Dictionary<string, object>>("FullName", "PetFamily.Core.Domain.Models.VolunteerAggregate.Volunteer.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("middle_name");
                        });

                    b.HasKey("Id")
                        .HasName("pK_volunteers");

                    b.ToTable("volunteers", (string)null);
                });

            modelBuilder.Entity("PetFamily.Core.Domain.Models.PetAggregate.Pet", b =>
                {
                    b.HasOne("PetFamily.Core.Domain.Models.VolunteerAggregate.Volunteer", "VolunteerNavigation")
                        .WithMany("Pets")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_pets_volunteers_volunteer_id");

                    b.OwnsOne("PetFamily.Core.Domain.Models.VolunteerAggregate.VO.HelpRequisites", "PetHelpRequisites", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid");

                            b1.HasKey("PetId")
                                .HasName("pK_pets");

                            b1.ToTable("pets");

                            b1.ToJson("help_requisites");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fK_pets_pets_PetId");

                            b1.OwnsMany("PetFamily.Core.Domain.Models.SharedKernel.VO.HelpRequisite", "ListHelpRequisites", b2 =>
                                {
                                    b2.Property<Guid>("HelpRequisitesPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)")
                                        .HasColumnName("description_help_requisite");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("name_help_requisite");

                                    b2.HasKey("HelpRequisitesPetId", "__synthesizedOrdinal");

                                    b2.ToTable("pets");

                                    b2.ToJson("help_requisites");

                                    b2.WithOwner()
                                        .HasForeignKey("HelpRequisitesPetId")
                                        .HasConstraintName("fK_pets_pets_HelpRequisitesPetId");
                                });

                            b1.Navigation("ListHelpRequisites");
                        });

                    b.OwnsOne("PetFamily.Core.Domain.Models.VolunteerAggregate.VO.Pet.PetSpeciesInfo", "SpeciesInfo", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("pet_id");

                            b1.Property<Guid>("BreedId")
                                .HasColumnType("uuid")
                                .HasColumnName("breed_id");

                            b1.Property<Guid>("SpecieId")
                                .HasColumnType("uuid")
                                .HasColumnName("species_id");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fK_pets_pets_pet_id");
                        });

                    b.OwnsOne("PetPhotos", "Photos", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("photos");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fK_pets_pets_pet_id");

                            b1.OwnsMany("PetFamily.Core.Domain.Models.VolunteerAggregate.VO.Pet.PetPhoto", "ListPetPhotos", b2 =>
                                {
                                    b2.Property<Guid>("PetPhotosPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("PathStorage")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("paths_in_storage");

                                    b2.HasKey("PetPhotosPetId", "__synthesizedOrdinal");

                                    b2.ToTable("pets");

                                    b2.ToJson("photos");

                                    b2.WithOwner()
                                        .HasForeignKey("PetPhotosPetId")
                                        .HasConstraintName("fK_pets_pets_PetPhotosPetId");
                                });

                            b1.Navigation("ListPetPhotos");
                        });

                    b.Navigation("PetHelpRequisites")
                        .IsRequired();

                    b.Navigation("Photos")
                        .IsRequired();

                    b.Navigation("SpeciesInfo")
                        .IsRequired();

                    b.Navigation("VolunteerNavigation");
                });

            modelBuilder.Entity("PetFamily.Core.Domain.Models.SpeciesAggregate.Entity.Breed", b =>
                {
                    b.HasOne("PetFamily.Core.Domain.Models.Species.Species", null)
                        .WithMany("Breeds")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_breeds_species_species_id");
                });

            modelBuilder.Entity("PetFamily.Core.Domain.Models.VolunteerAggregate.Volunteer", b =>
                {
                    b.OwnsOne("PetFamily.Core.Domain.Models.VolunteerAggregate.VO.SocialNetworks", "SocialNetworks", b1 =>
                        {
                            b1.Property<Guid>("VolunteerId")
                                .HasColumnType("uuid");

                            b1.HasKey("VolunteerId");

                            b1.ToTable("volunteers");

                            b1.ToJson("socialNetworks");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerId")
                                .HasConstraintName("fK_volunteers_volunteers_volunteer_id");

                            b1.OwnsMany("PetFamily.Core.Domain.Models.VolunteerAggregate.VO.SocialNetwork", "ListSocialNetworks", b2 =>
                                {
                                    b2.Property<Guid>("SocialNetworksVolunteerId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Link")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("link_social_network");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name_social_network");

                                    b2.HasKey("SocialNetworksVolunteerId", "__synthesizedOrdinal");

                                    b2.ToTable("volunteers");

                                    b2.ToJson("socialNetworks");

                                    b2.WithOwner()
                                        .HasForeignKey("SocialNetworksVolunteerId")
                                        .HasConstraintName("fK_volunteers_volunteers_SocialNetworksVolunteerId");
                                });

                            b1.Navigation("ListSocialNetworks");
                        });

                    b.OwnsOne("PetFamily.Core.Domain.Models.VolunteerAggregate.VO.HelpRequisites", "HelpRequisites", b1 =>
                        {
                            b1.Property<Guid>("VolunteerId")
                                .HasColumnType("uuid");

                            b1.HasKey("VolunteerId");

                            b1.ToTable("volunteers");

                            b1.ToJson("helpRequisites");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerId")
                                .HasConstraintName("fK_volunteers_volunteers_volunteer_id");

                            b1.OwnsMany("PetFamily.Core.Domain.Models.SharedKernel.VO.HelpRequisite", "ListHelpRequisites", b2 =>
                                {
                                    b2.Property<Guid>("HelpRequisitesVolunteerId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)")
                                        .HasColumnName("description_help_requisite");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("name_help_requisite");

                                    b2.HasKey("HelpRequisitesVolunteerId", "__synthesizedOrdinal");

                                    b2.ToTable("volunteers");

                                    b2.ToJson("helpRequisites");

                                    b2.WithOwner()
                                        .HasForeignKey("HelpRequisitesVolunteerId")
                                        .HasConstraintName("fK_volunteers_volunteers_HelpRequisitesVolunteerId");
                                });

                            b1.Navigation("ListHelpRequisites");
                        });

                    b.Navigation("HelpRequisites");

                    b.Navigation("SocialNetworks")
                        .IsRequired();
                });

            modelBuilder.Entity("PetFamily.Core.Domain.Models.Species.Species", b =>
                {
                    b.Navigation("Breeds");
                });

            modelBuilder.Entity("PetFamily.Core.Domain.Models.VolunteerAggregate.Volunteer", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
